version: '3.8'

services:
  backend:
    build: .
    container_name: job-board-backend
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: job-board-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
